plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.project_id
}

repositories {
	flatDir {
        dirs "local_maven"
    }
	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
	}
}

loom {
	mods {
		"${project.project_id}" {
			sourceSet sourceSets.main
		}
	}
}

sourceSets {
	main.java.srcDirs = ["src/main/java"]
	main.resources.srcDirs = ["src/main/resources"]
}


dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	
	implementation "net.fabricmc.fabric-api:fabric-api:${project.properties["fabric-api"]}"
	implementation "maven.modrinth:midnightlib:${project.properties["midnightlib"]}"
	include "maven.modrinth:midnightlib:${project.properties["midnightlib"]}"
}


processResources {
	inputs.property "maven_group", project.maven_group
	inputs.property "version", project.version
	inputs.property "project_id", project.project_id
	inputs.property "java_version", project.java_version
	inputs.property "loader_version", project.loader_version
	inputs.property "fabric_api_version", project.properties["fabric-api"].replaceFirst(/\+.*/, "")
	inputs.property "midnightlib_version", project.properties["midnightlib"].replaceFirst(/\+.*/, "")
	inputs.property "minecraft_compatible_range", Boolean.parseBoolean("${project.enforce_range}") ? project.minecraft_compatible_range : "\"*\""
	
	filesMatching("fabric.mod.json") {
		expand (
			maven_group: inputs.properties.maven_group,
			project_id: inputs.properties.project_id,
			version: inputs.properties.version,
			java_version: inputs.properties.java_version,
			loader_version: inputs.properties.loader_version,
			fabric_api_version: inputs.properties.fabric_api_version,
			midnightlib_version: inputs.properties.midnightlib_version,
			minecraft_compatible_range: inputs.properties.minecraft_compatible_range,
		)
	}
	
	filesMatching("*.mixins.json") {
		expand (
			maven_group: inputs.properties.maven_group,
			project_id: inputs.properties.project_id,
			java_version: JavaVersion.toVersion(project.java_version).toString().replace(".", "_"),
		)
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = Integer.parseInt(project.java_version)
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	// withSourcesJar()
	
	sourceCompatibility = JavaVersion.toVersion(project.java_version)
	targetCompatibility = JavaVersion.toVersion(project.java_version)
}

jar {
	inputs.property "archivesName", project.base.archivesName
	
	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}" }
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.base.archivesName
			from components.java
		}
	}
	
	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
