org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod Properties
mod_version = 1.5.5
maven_group = edu.jorbonism
project_id = cool_elytra

# Ralli driven values
minecraft_compatible_range=[">=26.3", "<26.4"]
enforce_range=true
minecraft_version=26.3
java_version=25
loom_version=1.16-SNAPSHOT
loader_version=0.19.5

# Dependencies
fabric-api=0.161.0+26.3
midnightlib=1.9.3+26.3-fabric
